---
configs:
  resources:
    vpc:
      vpc_name: "NB-production"
      cidr_block: "10.10.0.0/16"
      secondary_cidr_block: null

      # Subnets with private only access for server clusters in each AZ
      private_subnets:
        # for ECS instances
        private-subnet-1: "10.10.8.0/21" # 2,048

      # Subnets with public NAT gateway access for server clusters in each AZ
      public_subnets:
        public-subnet-1: "10.10.20.0/24"

      # Subnets for database clusters in each AZ
      database_subnets:
        database-subnet-1: "10.10.100.0/24"
      
      nat_subnets:
        nat-default: "10.10.16.0/24" # 256

    cce_turbo_cluster:
      # Subnet for the Pods
      subnet:
        name: "eni-subnet-0"
        cidr: 10.10.0.0/21
        gateway_ip: "10.10.0.1"
      
      node_pool:
        name: "nodepool"
        os: "CentOS 8.2"
        node_count: 10
        flavor_lookup:
          ap-southeast-3a: "c7n.xlarge.2"
          ap-southeast-3b: "c7n.large.4"
          ap-southeast-3c: "c7n.large.4"
          ap-southeast-3d: "c7n.xlarge.2"

        root_volume:
          size: 100
          volume_type: "SAS"

        data_volume:
          size: 100
          volume_type: "SAS"
    
    gaussdb:
      master_availability_zone: "ap-southeast-3a"
      availability_zone_mode: "multi"

    dds:
      mode: 'ReplicaSet'
      datastore:
        type: "DDS-Community"
        version: "3.4"
        storage_engine: "wiredTiger"
        
      flavor:
        type: "replica" 
        num: 3 
        storage: "ULTRAHIGH" 
        size: 500 
        spec_code: "dds.mongodb.s6.xlarge.2.repset" 

