---
configs:
  resources:
    vpc:
      vpc_name: "NB-production"
      cidr_block: "10.10.0.0/16"

      # Subnets with private only access for server clusters in each AZ
      private_subnets:
        # for CCE
        private-az-1: "10.10.0.0/21"

        # for ECS instances
        private-az1-3: "10.10.10.0/24"

      # Subnets with public NAT gateway access for server clusters in each AZ
      public_subnets:
        public-az1: "10.10.20.0/24"

      # Subnets for database clusters in each AZ
      database_subnets:
        database-az1: "10.10.100.0/24"

    cce_turbo_cluster:
      eni_subnet: "10.10.8.0/24"
      gateway_ip: "10.10.8.1"
      node_pool:
        name: "nodepool"
        os: "CentOS 8.2"
        initial_node_count: 10
        flavor_id: "c7n.large.2"
        min_node_count: 3
        max_node_count: 20
        scall_enable: true
        scale_down_cooldown_time: 100
        priority: 1
        type: "vm"

        root_volume:
          size: 100
          volume_type: "SAS"

        data_volume:
          size: 100
          volume_type: "SAS"
    
    gaussdb:
      master_availability_zone: "ap-southeast-3a"
      availability_zone_mode: "multi"

    dds:
      mode: 'ReplicaSet'
      datastore:
        type: "DDS-Community"
        version: "3.4"
        storage_engine: "wiredTiger"
        
      flavor:
        type: "replica" 
        num: 3 
        storage: "ULTRAHIGH" 
        size: 500 
        spec_code: "dds.mongodb.s6.xlarge.2.repset" 

