---
configs:
  resources:
    vpc:
      vpc_name: "NB-production"
      cidr_block: "10.10.0.0/16"

      # Subnets with private only access for server clusters in each AZ
      private_subnets:
        # for CCE
        private-az1-1: "10.10.0.0/24"
        private-az2-1: "10.10.1.0/24"
        private-az3-1: "10.10.2.0/24"
        private-az4-1: "10.10.3.0/24"
        private-az1-2: "10.10.4.0/24"
        private-az2-2: "10.10.5.0/24"
        private-az3-2: "10.10.6.0/24"
        private-az4-2: "10.10.7.0/24"
        
        # for ECS instances
        private-az1-3: "10.10.10.0/24"
        private-az2-3: "10.10.11.0/24"
        private-az3-3: "10.10.12.0/24"
        private-az4-3: "10.10.13.0/24"

      # Subnets with public NAT gateway access for server clusters in each AZ
      public_subnets:
        public-az1: "10.10.20.0/24"
        public-az2: "10.10.21.0/24"
        public-az3: "10.10.22.0/24"
        public-az4: "10.10.23.0/24"

      # Subnets for database clusters in each AZ
      database_subnets:
        database-az1: "10.10.100.0/24"
        database-az2: "10.10.101.0/24"
        database-az3: "10.10.102.0/24"
        database-az3: "10.10.103.0/24"

      # Additional subnets for NAT gateways
      nat_subway:
        public-nat-default: "10.10.200.0/24"
        private-nat-default: "10.10.201.0/24"

    cce_turbo_cluster:
      eni_subnet: "10.10.8.0/24"
      gateway_ip: "10.10.8.1"
      node_pool:
        name: "cce_node_pool"
        os: "CentOS 8.2"
        initial_node_count: 40
        flavor_id: "s3.2xlarge.2"
        min_node_count: 3
        max_node_count: 100
        scall_enable: true
        scale_down_cooldown_time: 100
        priority: 1
        type: "vm"

        root_volume:
          size: 100
          volume_type: "SAS"

        data_volume:
          size: 100
          volume_type: "SAS"
    
    gaussdb:
      master_availability_zone: "ap-southeast-3a"
      availability_zone_mode: "multi"

    dds:
      mode: 'ReplicaSet'
      datastore:
        type: "DDS-Community"
        version: "3.4"
        storage_engine: "wiredTiger"
        
      flavor:
        type: "replica" 
        num: 3 
        storage: "ULTRAHIGH" 
        size: 500 
        spec_code: "dds.mongodb.s6.xlarge.2.repset" 

