---
configs:
  resources:
    vpc:
      vpc_name: "NB-production"
      cidr_block: "10.10.0.0/16" #65,536

      secondary_cidr_block: null

      # Subnets with private only access for server clusters in each AZ
      private_subnets:
        # for ECS instances
        private-subnet-1: "10.10.8.0/21" # 2,048

      # Subnets with public NAT gateway access for server clusters in each AZ
      public_subnets:
        public-subnet-1: "10.10.20.0/24"

      # Subnets for database clusters in each AZ
      database_subnets:
        database-subnet-1: "10.10.100.0/24" # 256
      
      nat_subnets:
        nat-default: "10.10.16.0/24" # 256

    cce_turbo_cluster:
      keypair: "mykp"
      # Subnet for the Pods
      subnet:
        name: "eni-subnet-0"
        cidr: 10.10.0.0/21 #2,048
        gateway_ip: "10.10.0.1"
      
      node_pool:
      # flavor_lookup:
        #   ap-southeast-3a: "c7n.xlarge.2"
        #   ap-southeast-3b: "c7n.large.4"
        #   ap-southeast-3c: "c7n.large.4"
        #   ap-southeast-3d: "c7n.xlarge.2"
        - name: "nodepool"
          os: "CentOS 7.6"
          node_count: 10
          min_node_count: 10
          max_node_count: 70
          flavor_id: "c7n.xlarge.4"
          taints: []
          root_volume:
            size: 100
            volume_type: "SAS"

          data_volume:
            size: 100
            volume_type: "SAS"

        - name: "perp-matching"
          os: "CentOS 7.6"
          node_count: 2
          min_node_count: 1
          max_node_count: 20
          flavor_id: "c7n.2xlarge.2"
          labels:
            app: perp-matching
          taints:
          - key: app
            value: perp-matching
            effect: NoSchedule
          root_volume:
            size: 100
            volume_type: "SAS"
          data_volume:
            size: 100
            volume_type: "SAS"

        - name: "spot-matching"
          os: "CentOS 7.6"
          node_count: 2
          min_node_count: 1
          max_node_count: 20
          flavor_id: "c7n.2xlarge.2"
          labels:
            app: spot-matching
          taints:
          - key: app
            value: match-matching
            effect: NoSchedule
          root_volume:
            size: 100
            volume_type: "SAS"
          data_volume:
            size: 100
            volume_type: "SAS"

        - name: "match-matching-fusion"
          os: "CentOS 7.6"
          node_count: 2
          min_node_count: 1
          max_node_count: 20
          flavor_id: "c7n.2xlarge.2"
          labels:
            app: match-matching-fusion
          taints:
          - key: app
            value: match-matching-fusion
            effect: NoSchedule
          root_volume:
            size: 100
            volume_type: "SAS"
          data_volume:
            size: 100
            volume_type: "SAS"

        - name: "perp-matching-fusion"
          os: "CentOS 7.6"
          node_count: 2
          min_node_count: 1
          max_node_count: 20
          flavor_id: "c7n.2xlarge.2"
          labels:
            app: perp-matching-fusion
          taints:
          - key: app
            value: perp-matching-fusion
            effect: NoSchedule
          root_volume:
            size: 100
            volume_type: "SAS"
          data_volume:
            size: 100
            volume_type: "SAS"
    
    gaussdb:
      master_availability_zone: "ap-southeast-3a"
      availability_zone_mode: "multi"

    dds:
      mode: 'ReplicaSet'
      datastore:
        type: "DDS-Community"
        version: "3.4"
        storage_engine: "wiredTiger"
        
      flavor:
        type: "replica" 
        num: 3 
        storage: "ULTRAHIGH" 
        size: 500 
        spec_code: "dds.mongodb.s6.xlarge.2.repset"

    dcs:
      - name: redis
        whitelists:
          - group_name: "Pods"
            ip_address: ["10.10.0.0/21"]

      - name: redis_swap
        whitelists:
        - group_name: "Pods"
          ip_address: ["10.10.0.0/21"]

      - name: redis_spot
        whitelists:
          - group_name: "Pods"
            ip_address: ["10.10.0.0/21"]

    kafka:
      access_user: "user"
      password: "Kafkatest@123"
      manager_user: "kafka-user"
      manager_password: "Kafkatest@123"
      advertised_ips: ["", "www.terraform-test.com", "192.168.0.53"]

